name: Build and Test DRIVERLESS

permissions:
  contents: read
  packages: read


on:
  pull_request:
    types: [opened, reopened] 
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/arusfs/arus:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}



    steps:
    - name: Clone DRIVERLESS2, ARUSSim, DRIVERLESS_TESTS
      run: |
        mkdir -p /workspace/src
        cd /workspace/src

        git clone https://github.com/ARUSfs/DRIVERLESS2.git
        cd DRIVERLESS2
        git checkout develop
        cd ..

        git clone https://github.com/ARUSfs/ARUSSim.git
        git clone https://github.com/ARUSfs/DRIVERLESS_TESTS.git

    - name: Build workspace
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        cd /workspace
        colcon build

    - name: Source and run tests
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        cd /workspace
        source /workspace/install/setup.bash
        colcon test
        colcon test-result --all
